name: 'Cache'
on:
  push:
    tags:
      - 'v*'
jobs:
  cacheshell:
    name: Cache Shell
    uses: ./.github/workflows/⚡reusable-cacheshell.yaml
    secrets: inherit
  cachebuild:
    name: Cache Build
    uses: ./.github/workflows/⚡reusable-cachebuild.yaml
    secrets: inherit
